Built a successful non-complete GET request for Item
NaseemSrour/Deliveries pull request #29
Opened 2020-12-26 02:13 UTC by NaseemSrour

A draft PR for building a GET request for Item.
Server responses will always be JSONs.
Missing: returning the image. (idea: return img in a follow-up GET request after fetching the item).

2020-12-27 05:07 UTC, NaseemSrour commented
Rudy please review this, if you have any suggestions I would love to hear!
If everything's OK, let's close this PR and head to the testing. It is very important to build some good tests at this stage.

2020-12-30 16:28 UTC, rudyeila commented on server/resources/item_api.py
> +    # item_dict["image"] = my_item.image
Maybe encode the byte stream into a string and then decode it at the destination? 
Quick google search: 
https://stackoverflow.com/questions/57346338/how-to-return-image-stream-and-text-as-json-response-from-python-flask-api

2020-12-30 16:33 UTC, rudyeila commented on server/resources/item_api.py
> +def dictify_DBItem(my_item):
Instead of doing this manually, look into a json schema library, such as: 
https://marshmallow.readthedocs.io/en/stable/

2020-12-30 16:34 UTC, rudyeila commented on server/resources/item_api.py
> +    ################################### MISSING: Handle images
Same here, we need to look into an existing solution, such as marshmallow.

2020-12-30 16:39 UTC, rudyeila commented on server/resources/item_api.py
> +    ###################### NEED TO FIGURE OUT HOW TO RETURN AN IMAGE. Cannot put bytes in a json (which is called 'serialization')
Here is a stack overflow answer on how to do this with Marshmallow:
https://stackoverflow.com/questions/49752100/python-marshmallow-blob-bytes-field

2020-12-30 16:47 UTC, rudyeila reviewed
Looks good in general. If you can look into the points I mentioned regarding the data validation. 

I would also say, implement the equivalent item tests directly in this PR. No need for a separate PR. This all belongs to one issue. 

Do you want to also implement the update/delete methods now or later?

2020-12-30 16:47 UTC, rudyeila commented on server/resources/item_api.py
> +        self.reqparse.add_argument('item_id', type = int, required = True, help = {"The requested item's ID number"})
Instead of this we could use a validation Scheme, like Marshmallow. It allows for more powerful parsing. 
There is also a wrapper that integrates marshmallow with Flask:
https://flask-marshmallow.readthedocs.io/en/latest/

This might be something we want to checkout. Also the following is a flask extension for better SQL DB integration (It says SQLAlchemy, is that different from mySQL)? 
https://flask-sqlalchemy.palletsprojects.com/en/2.x/

2020-12-30 19:03 UTC, NaseemSrour commented on server/resources/item_api.py
> +def dictify_DBItem(my_item):
There's a built-in method called myVar.__dict__
See lines 58 + 59 for a clear view of it. I used the custom one to exclude the image field.

2020-12-30 19:12 UTC, NaseemSrour commented on server/resources/item_api.py
> +    ###################### NEED TO FIGURE OUT HOW TO RETURN AN IMAGE. Cannot put bytes in a json (which is called 'serialization')
The question is; do we want a string of length thousands in our json? I believe we will need to look at the sent jsons when developing, in Postman for example, and having a very long string in it isn't ideal. What do you think?

I was thinking in fact instead of having the bytes as is (or as a string) directly in the json, we could issue a follow-up HTTP request that'll upload the image and save it on the machine, and thus we can read it as bytes and insert it into the database.

2020-12-30 19:19 UTC, NaseemSrour commented on server/resources/item_api.py
> +    ################################### MISSING: Handle images
As I've understood from marshmallow, it'll ease the conversion from dictionary (json) to DBItem type, AND validate the fields' values?

2020-12-30 19:30 UTC, NaseemSrour commented on server/resources/item_api.py
> +        self.reqparse.add_argument('item_id', type = int, required = True, help = {"The requested item's ID number"})
Reqparse is from the Flask documentation, to validate the requests' incoming fields.
SQLAlchemy is a library to deal with our DB entities in Python as objects and forget about the SQL beneath.

Adopting these requires learning them, and changing our working code. I suggest we ( I ) write a good test for item_api, or DBItem, see how how it turns out, and after that we can branch off and try to replace our code with new one using SQLAlchemy and Marshmallow.

This reminds me to ask you: when working with a new library, like let's say PyTest, I personally haven't found it easy to go over the docs and then try to write something up, as I must read a bit into how things work there before I start writing my code. Any suggestions how to adopt new libraries more easily? How do you personally do it? I'd be glad for some insights!

2020-12-31 10:27 UTC, rudyeila commented on server/resources/item_api.py
> +    ################################### MISSING: Handle images
Yes exactly. You basically define the JSON structure of the object in a schema and the schema then handles the validation of the json and allows you to convert back and forth between a json and an object representation.

2020-12-31 10:28 UTC, rudyeila commented on server/resources/item_api.py
> +    ###################### NEED TO FIGURE OUT HOW TO RETURN AN IMAGE. Cannot put bytes in a json (which is called 'serialization')
Hmm ok, good point. I'm not sure, I haven't had to do something like this before. But I am sure this is something that is usually done pretty much in every server, so there must be a standard solution for this. A bit of googling should help here.

2020-12-31 10:37 UTC, rudyeila commented on server/resources/item_api.py
> +        self.reqparse.add_argument('item_id', type = int, required = True, help = {"The requested item's ID number"})
Regparse is fine for simple usecases, but as soon as things get complicated, say you have a nested json object inside of another, then you can't validate that. you then need a more complex library. 

You can leave things as they are now, that's fine, however, I can tell from experience, that is better to use a proven solution from the get go rather than reinventing the wheel, because sooner or later, things will get complicated and you'll need some of the features offered by libraries like SQLAlchemy, and then to reintegrate something like that back into the code will cause a lot of headaches.

I recently had something like this, where I thought I didn't need to persist data at the beginning and thought if I decided against that, I can easily integrate a persistence library, but unfortunately it was way too complicated at that stage. 

But as you said, leave it like this for this PR, write the tests and then after this we can see how to move forward. 

Regarding learning new libraries, you really don't need to. It is very difficult to go through the entire documentation and understand everything at the beginning. The way I do it is, when I have a problem, I do a bit of googling, see what libraries get recommended, then go to that library and read the "Quick Start" section, which usually takes like 5 minutes, and that usually gives me an idea if the library does what I need. Usually the quick start section gives you all the information you need to get set up. When I have a more specific problem later on, then I try to find the relevant part in the documentation and/or do a bit of googling.

So for Pytest for example, this is basically all you need to get started: https://docs.pytest.org/en/stable/getting-started.html
It shouldn't take more than 5 minutes to read and you should be able to write simple testcases using this. The flask pytest stuff is a bit more complicated, but I already had to bang my head against the wall a few times to get it, but now I do, so you don't have to :D That's why I setup the tests. You can only look at the example I made and create more.

2020-12-31 10:38 UTC, rudyeila commented on server/resources/item_api.py
> +def dictify_DBItem(my_item):
This built in method will only work for very simple objects. You'll run into issues as soon as they get slightly more complicated. E.g. referencing other objects.

2021-01-03 14:30 UTC, NaseemSrour commented
See if you have any ideas for these test_get and test_post functions.

2021-01-04 08:46 UTC, rudyeila requested changes

2021-01-04 08:46 UTC, rudyeila commented on server/tests/test_resources/test_item_api.py
> +def test_get_item(client: FlaskClient):
Looks good. 

One little suggestion: usually a separate DB is used for testing. You don't want to mix the "production/development" DB with the testing one, since you'll be adding and removing resources and that shouldn't affect the actual database. 

Also, I think it is is best to populate the DB independently for every test case. So in every unit test, you should assume that the DB is empty. This gives you a baseline to work with. Then for the get test for example, you first add an item or a few to the DB (You can write a utility function, or a fixture to always do this for you before the test), and then you test getting that item.

2021-01-05 12:45 UTC, NaseemSrour commented on server/tests/test_resources/test_item_api.py
> +def test_get_item(client: FlaskClient):
This is a very good idea! I wrote this test & I physically tested that the item is inserted into the database that I already have on my PC (which is populated already).
We could built a new instance of the DB as a _test_db_, and have ready functions/scripts that fill it with needed data for tests.

2021-01-05 12:52 UTC, rudyeila commented on server/tests/test_resources/test_item_api.py
> +def test_get_item(client: FlaskClient):
Yes the idea is that the tests should be able to run independently of the machine, e.g. the Github CI Pipeline. Also the order in which the tests are ran should be irrelevant. That's why I think it's better to populate the database for each testcase and handle it independently. 

Yeah we can use the same funcitons to fill the data, by using a new test instance like you suggest it. We just need to figure out how to change the used database based on whether we are testing or running the server.

2021-01-05 12:58 UTC, NaseemSrour commented on server/tests/test_resources/test_item_api.py
> +def test_get_item(client: FlaskClient):
This is the goal of issue #31, there's something called mock tests which I haven't read into it yet, but seems like our target for this type of issue.

2021-01-17 12:45 UTC, merged